/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supplier;

import bill.db_Connection;
import customer.Customer_New_details;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Jagmeet sandhu
 */
public class supplier_add extends javax.swing.JFrame {
db_Connection dbconn=null;
        
        
    /**
     * Creates new form supplier_add
     */ supplier_base s_s;
    public supplier_add(supplier_base ss) {
        dbconn=new db_Connection();
        initComponents();
        setSize(500,600);
        this.s_s=ss;
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    public supplier_add() {
        dbconn=new db_Connection();
        initComponents();
        setSize(500,600);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_supplier_name = new javax.swing.JTextField();
        tf_supplier_address = new javax.swing.JTextField();
        tf_supplier_city = new javax.swing.JTextField();
        tf_supplier_mobile = new javax.swing.JTextField();
        tf_supplier_email = new javax.swing.JTextField();
        tf_supplier_state = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_supplier_type = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("New Supplier");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 190, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setText("Supplier Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 80, 120, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 120, 120, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("City");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 160, 120, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Mobile no.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 240, 120, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("e-mail");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 280, 120, 30);
        getContentPane().add(tf_supplier_name);
        tf_supplier_name.setBounds(210, 80, 170, 30);
        getContentPane().add(tf_supplier_address);
        tf_supplier_address.setBounds(210, 120, 170, 30);
        getContentPane().add(tf_supplier_city);
        tf_supplier_city.setBounds(210, 160, 170, 30);
        getContentPane().add(tf_supplier_mobile);
        tf_supplier_mobile.setBounds(210, 240, 170, 30);
        getContentPane().add(tf_supplier_email);
        tf_supplier_email.setBounds(210, 280, 170, 30);

        tf_supplier_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Madya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Orissa", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Tripura", "Uttaranchal", "Uttar Pradesh", "West Bengal" }));
        tf_supplier_state.setSelectedIndex(20);
        getContentPane().add(tf_supplier_state);
        tf_supplier_state.setBounds(210, 200, 170, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("State");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 200, 80, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setText("Type");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 320, 80, 30);

        tf_supplier_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manufacturer", "Distibutor" }));
        getContentPane().add(tf_supplier_type);
        tf_supplier_type.setBounds(210, 320, 170, 30);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 380, 51, 23);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 380, 55, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String name=tf_supplier_name.getText();
            String address=tf_supplier_address.getText();
            String city=tf_supplier_city.getText();
            String state=(String)tf_supplier_state.getSelectedItem();
            String mobile1=tf_supplier_mobile.getText();
            String email=tf_supplier_email.getText();
            String type=(String)tf_supplier_type.getSelectedItem();
            Pattern pattern = Pattern.compile("\\d{10}");
            Matcher matcher = pattern.matcher(mobile1);
            if(name.equals("") || address.equals("") || city.equals("") || state.equals("") || mobile1.equals("") )
            {
                JOptionPane.showMessageDialog(this, "please enter all details");
            }
            else if ((email.length() !=0)  &&( !email.contains("@") || !email.contains("."))) 
                     {
                         JOptionPane.showMessageDialog(this, "please enter a valid email address");
                         tf_supplier_email.setText("");
                     }

            else if (!matcher.matches())
                   {
                       JOptionPane.showMessageDialog(this, "enter correct mobile number");
                       tf_supplier_mobile.setText("");
                   }
             else
                   {
                try {
                    Connection conn = db_Connection.getconnectiom();
                    Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    try (ResultSet rs = stmt.executeQuery("select * from supplier_details")) {
                        System.out.println("Resultset created");
                        rs.moveToInsertRow();
                    	rs.updateString("supplier_name", name);
                        rs.updateString("type",type);
                        rs.updateString("address", address);
                        rs.updateString("city", city);
                        rs.updateString("state", state);
                        rs.updateString("mobile_no", mobile1);
                        rs.updateString("email",email );
                        rs.insertRow();
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Customer_New_details.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Customer Added Successfully");
                int option=JOptionPane.YES_NO_OPTION;
                JOptionPane.showConfirmDialog(this, "want to add another supplier", "Add new Supplier", option);
                       System.out.println(""+option);
                if(option==9)
                {
                    tf_supplier_name.setText("");
                    tf_supplier_address.setText("");
                    tf_supplier_city.setText("");
                    tf_supplier_email.setText("");
                    tf_supplier_mobile.setText("");
                    
                 }
                else
                {
                    this.dispose();
                    if(s_s!=null)
                    {
                        this.s_s.update_supplier_list();                    
                    }
                    
                }
                   }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(supplier_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(supplier_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(supplier_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(supplier_add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new supplier_add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tf_supplier_address;
    private javax.swing.JTextField tf_supplier_city;
    private javax.swing.JTextField tf_supplier_email;
    private javax.swing.JTextField tf_supplier_mobile;
    private javax.swing.JTextField tf_supplier_name;
    private javax.swing.JComboBox<String> tf_supplier_state;
    private javax.swing.JComboBox<String> tf_supplier_type;
    // End of variables declaration//GEN-END:variables
}
